# DO NOT CHANGE! If changed, it can break plugins.
# Plugins rely on this version number so they know which features work.
internalversion: "1.9.3"

# Variables to use in custom messages. Don’t change unless you’re redoing the messages that use these variables as well
sendervar: "%u"
versionvar: "%v"

# KEEP THIS SAFE! If shared, others can send messages using your bot.
token: ""

# The URL that allows you to invite the bot to other Discord servers.
# The second key is only used if the user wants the full URL, and is not normally visible.
# Leave one or the other blank to disable the use of it.
inviteurl: "http://bit.ly/2chWygB"
inviteurlfull: "https://discordapp.com/oauth2/authorize?&client_id=222370039075045387&scope=bot"

# What character should precede your Onebot commands?
# Default is an asterisk (*)
prefix: "*"

# Which channel should the bot log events to?
# Set to "console" to log to console (will be added in 1.10 version, NYI)
logchannel: "222393788755083264"

# Should we automatically delete log messages after a specified amount of time? (NYI)
# Set to -1 to never purge.
logpurgetime: "-1"

# Should we automatically delete log messages after a specified amount of log messgaes? (NYI)
# Set to -1 to never purge.
logpurgecount: "-1"

# What username would you like to use for the hoster name? (Not yet implemented)
hosterdiscord: ""
hostergithub: ""

# Test message on start-up. Leave blank for default.
startupconsole: ""
startupevent: ""

# Version command: variables don't work right now.
versionevent: "%u asked for the version number."
versionreply: "I’m running the version v%v!"

# If true, uses HTTPS by default instead of HTTP when accessing the internet.
prefersecure: true

# Permission Precedence variable. Left variables take priority over right variables. 
permprecedence:'s:c:r:u'
